//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Project_FinishEntities : DbContext
    {
        public Project_FinishEntities()
            : base("name=Project_FinishEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Grade_Tbl> Grade_Tbl { get; set; }
        public virtual DbSet<Presence_Tbl> Presence_Tbl { get; set; }
        public virtual DbSet<Student_Tbl> Student_Tbl { get; set; }
        public virtual DbSet<StudentsClassroom_Tbl> StudentsClassroom_Tbl { get; set; }
    }
}
