//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;

    public partial class Student_Tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student_Tbl()
        {
            this.Presence_Tbl = new HashSet<Presence_Tbl>();
        }

        public string Student_ID { get; set; }
        public string Student_Name { get; set; }
        public string Student_Image { get; set; }
        public Nullable<int> Student_Grade_Code { get; set; }
        public byte[] DistancePoint { get; set; }
        public string DistPoint { get; set; }

        public virtual Grade_Tbl Grade_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presence_Tbl> Presence_Tbl { get; set; }
    }
}
